openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://geekmj-javascript-guides-r75vjjr7jr2jxp-8080.githubpreview.dev
paths:
  /hello:
    get:
      responses:
        '200':
          description: OK
